ECommerceRemake/Models/SanPham.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerceRemake.Models
{
    public class SanPham
    {
        [Key]
        [Required]
        public int MaSP { get; set; }
        [Required, DisplayName("Tên Sản Phẩm")]
        public string TenSP { get; set; }
        [Required,DisplayName("Giá")]
        [DataType(DataType.Currency)]
        public decimal DonGia { get; set; }
        [DisplayName("Ngày Cập Nhật")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime NgayCapNhat { get; set; }
        [DisplayName("Cấu Hình")]
        public string CauHinh { get; set; }
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }
        [DisplayName("Hình ảnh sản phẩm")]
        public string HinhAnh { get; set; }
        [DisplayName("Số lượng tồn"),Range(0,9999)]
        public int SoLuongTon { get; set; }
        [DisplayName("Số lượt xem"), Range(0, 999999999999999)]
        public int LuotXem { get; set; }
        [DisplayName("Số lượt bình luận"), Range(0, 999999999999999)]
        public int LuotBinhLuan { get; set; }
        [DisplayName("Số lần mua"), Range(0, 999999999999999)]
        public int SoLanMua { get; set; }
        [DisplayName("Mới?"), Range(0,1)]
        public int Moi { get; set; }
        [DisplayName("Mã Loại")]
        public int MaLoai { get; set; }
        [DisplayName("Đã Xóa?")]
        public bool DaXoa { get; set; }

        //public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        //public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        //public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        //[Display(Name = "Loại sản phẩm")]
        //public virtual LoaiSP loaiSP { get; set; }
    }
}

ECommerceRemake/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ECommerceRemake.Data;
using ECommerceRemake.Models;

namespace ECommerceRemake.Controllers
{
    public class SanPhamsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SanPhamsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SanPhams
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.SanPham.ToListAsync());
        //}

        public async Task<IActionResult> Index(string id, int? page=null, int? pagesize =10)
        {
            var lstSp = from sp in _context.SanPham
                        select sp;
            if (!String.IsNullOrEmpty(id))
            {
                lstSp = lstSp.Where(s => s.TenSP.Contains(id));
            }
            return View(await lstSp.ToListAsync());
        }

        // GET: SanPhams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPham
                .FirstOrDefaultAsync(m => m.MaSP == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: SanPhams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSP,TenSP,DonGia,NgayCapNhat,CauHinh,MoTa,HinhAnh,SoLuongTon,LuotXem,LuotBinhLuan,SoLanMua,Moi,MaLoai,DaXoa")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sanPham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sanPham);
        }

        // GET: SanPhams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPham.FindAsync(id);
            if (sanPham == null)
            {
                return NotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaSP,TenSP,DonGia,NgayCapNhat,CauHinh,MoTa,HinhAnh,SoLuongTon,LuotXem,LuotBinhLuan,SoLanMua,Moi,MaLoai,DaXoa")] SanPham sanPham)
        {
            if (id != sanPham.MaSP)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sanPham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamExists(sanPham.MaSP))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPham
                .FirstOrDefaultAsync(m => m.MaSP == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sanPham = await _context.SanPham.FindAsync(id);
            _context.SanPham.Remove(sanPham);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SanPhamExists(int id)
        {
            return _context.SanPham.Any(e => e.MaSP == id);
        }
    }
}

ECommerceRemake/Views/SanPhams/Create.cshtml
@model ECommerceRemake.Models.SanPham

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SanPham</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenSP" class="control-label"></label>
                <input asp-for="TenSP" class="form-control" />
                <span asp-validation-for="TenSP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DonGia" class="control-label"></label>
                <input asp-for="DonGia" class="form-control" />
                <span asp-validation-for="DonGia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayCapNhat" class="control-label"></label>
                <input asp-for="NgayCapNhat" class="form-control" />
                <span asp-validation-for="NgayCapNhat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CauHinh" class="control-label"></label>
                <input asp-for="CauHinh" class="form-control" />
                <span asp-validation-for="CauHinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HinhAnh" class="control-label"></label>
                <input asp-for="HinhAnh" class="form-control" />
                <span asp-validation-for="HinhAnh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongTon" class="control-label"></label>
                <input asp-for="SoLuongTon" class="form-control" />
                <span asp-validation-for="SoLuongTon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuotXem" class="control-label"></label>
                <input asp-for="LuotXem" class="form-control" />
                <span asp-validation-for="LuotXem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuotBinhLuan" class="control-label"></label>
                <input asp-for="LuotBinhLuan" class="form-control" />
                <span asp-validation-for="LuotBinhLuan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLanMua" class="control-label"></label>
                <input asp-for="SoLanMua" class="form-control" />
                <span asp-validation-for="SoLanMua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Moi" class="control-label"></label>
                <input asp-for="Moi" class="form-control" />
                <span asp-validation-for="Moi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLoai" class="control-label"></label>
                <input asp-for="MaLoai" class="form-control" />
                <span asp-validation-for="MaLoai" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="DaXoa" /> @Html.DisplayNameFor(model => model.DaXoa)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECommerceRemake/Views/SanPhams/Delete.cshtml
@model ECommerceRemake.Models.SanPham

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenSP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DonGia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CauHinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CauHinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LuotXem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuotXem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LuotBinhLuan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuotBinhLuan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLanMua)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLanMua)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Moi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Moi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaLoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaLoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DaXoa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DaXoa)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaSP" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ECommerceRemake/Views/SanPhams/Details.cshtml
@model ECommerceRemake.Models.SanPham

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenSP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DonGia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CauHinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CauHinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LuotXem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuotXem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LuotBinhLuan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LuotBinhLuan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLanMua)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLanMua)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Moi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Moi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaLoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaLoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DaXoa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DaXoa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MaSP">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ECommerceRemake/Views/SanPhams/Edit.cshtml
@model ECommerceRemake.Models.SanPham

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SanPham</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaSP" />
            <div class="form-group">
                <label asp-for="TenSP" class="control-label"></label>
                <input asp-for="TenSP" class="form-control" />
                <span asp-validation-for="TenSP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DonGia" class="control-label"></label>
                <input asp-for="DonGia" class="form-control" />
                <span asp-validation-for="DonGia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayCapNhat" class="control-label"></label>
                <input asp-for="NgayCapNhat" class="form-control" />
                <span asp-validation-for="NgayCapNhat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CauHinh" class="control-label"></label>
                <input asp-for="CauHinh" class="form-control" />
                <span asp-validation-for="CauHinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HinhAnh" class="control-label"></label>
                <input asp-for="HinhAnh" class="form-control" />
                <span asp-validation-for="HinhAnh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuongTon" class="control-label"></label>
                <input asp-for="SoLuongTon" class="form-control" />
                <span asp-validation-for="SoLuongTon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuotXem" class="control-label"></label>
                <input asp-for="LuotXem" class="form-control" />
                <span asp-validation-for="LuotXem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LuotBinhLuan" class="control-label"></label>
                <input asp-for="LuotBinhLuan" class="form-control" />
                <span asp-validation-for="LuotBinhLuan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLanMua" class="control-label"></label>
                <input asp-for="SoLanMua" class="form-control" />
                <span asp-validation-for="SoLanMua" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Moi" class="control-label"></label>
                <input asp-for="Moi" class="form-control" />
                <span asp-validation-for="Moi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLoai" class="control-label"></label>
                <input asp-for="MaLoai" class="form-control" />
                <span asp-validation-for="MaLoai" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="DaXoa" /> @Html.DisplayNameFor(model => model.DaXoa)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECommerceRemake/Views/SanPhams/Index.cshtml
@model IEnumerable<ECommerceRemake.Models.SanPham>

@{
}

<h1>Index</h1>
<p>
    <a asp-action="Create">Thêm mới</a>
</p>
<form asp-controller="SanPhams" asp-action="Index" method="post">
    <p>
        Title: <input type="text" name="id" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table table-hover table-sm">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenSP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DonGia)
            </th>
@*            <th>
                @Html.DisplayNameFor(model => model.NgayCapNhat)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.CauHinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MoTa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HinhAnh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLuongTon)
            </th>
@*            <th>
                @Html.DisplayNameFor(model => model.LuotXem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LuotBinhLuan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLanMua)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Moi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaLoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DaXoa)
            </th>*@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr >
            <td>
                @Html.DisplayFor(modelItem => item.TenSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonGia)
            </td>
@*            <td>
                @Html.DisplayFor(modelItem => item.NgayCapNhat)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.CauHinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MoTa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HinhAnh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuongTon)
            </td>
@*            <td>
                @Html.DisplayFor(modelItem => item.LuotXem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LuotBinhLuan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLanMua)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Moi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaLoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaXoa)
            </td>*@
            <td>
                @*<a asp-action="Edit" asp-route-id="@item.MaSP">Sửa</a> |*@
                <a asp-action="Details" asp-route-id="@item.MaSP" class="btn btn-sm btn-outline-info">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.MaSP" class="btn btn-sm btn-outline-danger">Xóa</a>
            </td>
        </tr>
}       <tr><td colspan="6"><strong>Tổng số: @Model.Count()</strong></td></tr>
    </tbody>
</table>